version: "3.4"

services:
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    environment:
      - DATABASE_URL="jdbc:postgresql://db:5432/fusionauth"
      - DATABASE_ROOT_USER=fusionauth
      - DATABASE_ROOT_PASSWORD=pPK3PjQWVijFgiV
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      - FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      - FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      - FUSIONAUTH_URL: http://fusionauth:9011
    networks:
     - db
     - search
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config


  db:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=fusionauth
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - search
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data



networks:
  db:
    driver: bridge
  search:
    driver: bridge

volumes:
  db_data:
  es_data:
  fa_config:
